"""DRL-initialized CR-MODE optimizer."""
from __future__ import annotations

from src.optimizers.cr_mode import CRMode
from src.rl_init.population_generator import DRLInitPopulationGenerator


class DRLInitCRMode(CRMode):
    """CR-MODE whose initial population is generated by PPO initialization."""

    def __init__(self, ctx, config):
        super().__init__(ctx, config)
        self.init_metrics = []
        self.init_training_log = []
        self.init_train_seconds = 0.0
        self.init_generation_seconds = 0.0
        self.init_policy_path = ""
        self.accepted_counts = {"drl": 0, "heuristic": 0, "random": 0}
        self.loaded_checkpoint = False
        self.policy_source = ""
        self.checkpoint_path = ""
        self.torch_available = False
        self.drl_init_summary = {}
        self.checkpoint_compatible = False
        self.checkpoint_skip_reason = ""
        self.checkpoint_error = ""
        self.checkpoint_mode = ""
        self.config_hash = ""
        self.checkpoint_load_seconds = 0.0
        self.pretrain_seconds = 0.0

    def initialize_population(self):
        generator = DRLInitPopulationGenerator(self.ctx, self.config)
        population = generator.generate(self.NP)
        self.init_metrics = generator.init_metrics
        self.init_training_log = generator.training_log
        self.init_train_seconds = float(generator.train_seconds)
        self.init_generation_seconds = float(getattr(generator, "generation_seconds", 0.0))
        self.init_policy_path = generator.policy_path
        self.accepted_counts = generator.accepted_counts
        self.loaded_checkpoint = bool(getattr(generator, "loaded_checkpoint", False))
        self.policy_source = getattr(generator, "policy_source", "trained")
        self.checkpoint_path = getattr(generator, "policy_path", "")
        self.torch_available = bool(getattr(generator, "torch_available", False))
        self.checkpoint_compatible = bool(getattr(generator, "checkpoint_compatible", False))
        self.checkpoint_skip_reason = getattr(generator, "checkpoint_skip_reason", "")
        self.checkpoint_error = getattr(generator, "checkpoint_error", "")
        self.checkpoint_mode = getattr(generator, "checkpoint_mode", "")
        self.config_hash = getattr(generator, "config_hash", "")
        self.checkpoint_load_seconds = float(getattr(generator, "checkpoint_load_seconds", 0.0))
        self.pretrain_seconds = float(getattr(generator, "pretrain_seconds", 0.0))
        generator.save_artifacts(self.config.get("runtime", {}).get("output_dir", "results"))
        self.drl_init_summary = getattr(generator, "summary", {})
        return population
