"""DRL-initialized CR-MODE optimizer."""
from __future__ import annotations

from src.optimizers.cr_mode import CRMode
from src.rl_init.population_generator import DRLInitPopulationGenerator


class DRLInitCRMode(CRMode):
    """CR-MODE whose initial population is generated by PPO initialization."""

    def __init__(self, ctx, config):
        super().__init__(ctx, config)
        self.init_metrics = []
        self.init_training_log = []
        self.init_train_seconds = 0.0
        self.init_generation_seconds = 0.0
        self.init_policy_path = ""
        self.accepted_counts = {"drl": 0, "heuristic": 0, "random": 0}
        self.loaded_checkpoint = False

    def initialize_population(self):
        generator = DRLInitPopulationGenerator(self.ctx, self.config)
        population = generator.generate(self.NP)
        self.init_metrics = generator.init_metrics
        self.init_training_log = generator.training_log
        self.init_train_seconds = float(generator.train_seconds)
        self.init_generation_seconds = float(getattr(generator, "generation_seconds", 0.0))
        self.init_policy_path = generator.policy_path
        self.accepted_counts = generator.accepted_counts
        self.loaded_checkpoint = bool(getattr(generator, "loaded_checkpoint", False))
        generator.save_artifacts(self.config.get("runtime", {}).get("output_dir", "results"))
        return population
